"""Statewide NH site catalog — every hiking region NH Fish & Game SAR responds to.

Extends the Presidential-Range core (build_sim_topology.SITES) to the full
state: Franconia, Pemigewasset, Kancamagus/Sandwich, Moosilauke, Carters/
Moriah, Mahoosucs, Kilkenny/North Country, Waumbek/Cherry, Carrigain/Willey,
Cardigan, Sunapee/Ragged, Belknaps, Chocorua, Monadnock, Pack Monadnock,
Smarts (AT corridor).

Placement doctrine (same as the core): gateways only where grid power +
internet exist today (tram/ski summit stations, state-park HQs, staffed
lodges, town facilities); ridge relays on named summits/cols along SAR
corridors; valley nodes at the trailheads crews actually stage from.
Coordinates are map-derived (±~300 m) — survey on deployment.

Each region is a largely self-contained RF island with its own MQTT gateway;
inter-region links are not expected (and honestly reported as absent).
"""

def _s(lat, lon, hg, power, mqtt, cat, label):
    return {"lat": lat, "lon": lon, "hg_m": hg, "power": power,
            "mqtt_uplink": mqtt, "category": cat, "label": label}


STATEWIDE_SITES = {
    # ── Franconia Ridge / Cannon–Kinsman ─────────────────────────────────────
    "cannon_tram_top":    _s(44.15650, -71.69860, 6.0, "grid", True, "gateway",
                             "Cannon Mtn tramway summit station"),
    "lafayette_place":    _s(44.14180, -71.68110, 4.0, "grid", True, "gateway",
                             "Lafayette Place campground (I-93)"),
    "flume_vc":           _s(44.09750, -71.68110, 4.0, "grid", True, "gateway",
                             "Flume Gorge Visitor Center"),
    "greenleaf_hut":      _s(44.16090, -71.66020, 3.0, "solar", False, "hut",
                             "AMC Greenleaf hut"),
    "lonesome_lake_hut":  _s(44.13810, -71.70330, 3.0, "solar", False, "hut",
                             "AMC Lonesome Lake hut"),
    "lafayette_summit":   _s(44.16080, -71.64450, 3.0, "solar", False, "ridge",
                             "Mt. Lafayette summit"),
    "little_haystack":    _s(44.14480, -71.64520, 3.0, "solar", False, "ridge",
                             "Little Haystack (Falling Waters jct)"),
    "liberty_summit":     _s(44.11540, -71.64310, 3.0, "solar", False, "ridge",
                             "Mt. Liberty summit"),
    "kinsman_n":          _s(44.12740, -71.73700, 3.0, "solar", False, "ridge",
                             "North Kinsman summit"),
    "kinsman_pond":       _s(44.12140, -71.72110, 3.0, "solar", False, "shelter",
                             "Kinsman Pond shelter"),
    # ── Pemigewasset / Twins–Bonds–Zealand ───────────────────────────────────
    "lincoln_woods_th":   _s(44.06360, -71.58880, 4.0, "grid", True, "gateway",
                             "Lincoln Woods ranger station (Kanc)"),
    "garfield_summit":    _s(44.18690, -71.61050, 3.0, "solar", False, "ridge",
                             "Mt. Garfield summit"),
    "galehead_hut":       _s(44.18790, -71.56880, 3.0, "solar", False, "hut",
                             "AMC Galehead hut"),
    "south_twin":         _s(44.18760, -71.55400, 3.0, "solar", False, "ridge",
                             "South Twin summit"),
    "guyot_summit":       _s(44.16250, -71.53400, 3.0, "solar", False, "ridge",
                             "Mt. Guyot (Bonds jct)"),
    "bondcliff":          _s(44.14100, -71.54360, 3.0, "solar", False, "ridge",
                             "Bondcliff"),
    "zealand_hut":        _s(44.19640, -71.49400, 3.0, "solar", False, "hut",
                             "AMC Zealand Falls hut"),
    "zeacliff":           _s(44.18950, -71.49080, 3.0, "solar", False, "ridge",
                             "Zeacliff outlook"),
    "hancock_th":         _s(44.10630, -71.51810, 3.0, "solar", False, "valley",
                             "Hancock Notch trailhead (Kanc hairpin)"),
    # ── Carrigain / Willey (Crawford south + Sawyer River SAR zone) ──────────
    "carrigain_summit":   _s(44.09430, -71.44660, 10.0, "solar", False, "ridge",
                             "Mt. Carrigain (fire tower)"),
    "willey_summit":      _s(44.16340, -71.44430, 3.0, "solar", False, "ridge",
                             "Mt. Willey summit"),
    "sawyer_river_th":    _s(44.06840, -71.42500, 3.0, "solar", False, "valley",
                             "Sawyer River Rd trailhead"),
    # ── Kancamagus / Osceola–Tripyramid–Sandwich ─────────────────────────────
    "waterville_valley":  _s(43.95060, -71.50310, 4.0, "grid", True, "gateway",
                             "Waterville Valley town center"),
    "kanc_pass":          _s(44.03910, -71.54050, 3.0, "solar", False, "valley",
                             "Kancamagus Pass overlook"),
    "osceola_summit":     _s(43.98410, -71.53370, 3.0, "solar", False, "ridge",
                             "Mt. Osceola summit (old tower site)"),
    "greeley_ponds":      _s(44.02010, -71.51730, 3.0, "solar", False, "shelter",
                             "Greeley Ponds site"),
    "tripyramid_n":       _s(43.97740, -71.44300, 3.0, "solar", False, "ridge",
                             "North Tripyramid summit"),
    "sandwich_dome":      _s(43.89150, -71.45510, 3.0, "solar", False, "ridge",
                             "Sandwich Dome summit"),
    "whiteface_summit":   _s(43.93700, -71.41060, 3.0, "solar", False, "ridge",
                             "Mt. Whiteface south ledges"),
    "passaconaway":       _s(43.95470, -71.38100, 3.0, "solar", False, "ridge",
                             "Mt. Passaconaway summit"),
    "ferncroft_th":       _s(43.91380, -71.36400, 3.0, "solar", False, "valley",
                             "Ferncroft trailhead (Wonalancet)"),
    "welch_dickey_th":    _s(43.90410, -71.58810, 3.0, "solar", False, "valley",
                             "Welch-Dickey loop trailhead"),
    # ── Chocorua ─────────────────────────────────────────────────────────────
    "chocorua_summit":    _s(43.95440, -71.39750, 3.0, "solar", False, "ridge",
                             "Mt. Chocorua summit cone"),
    "piper_th":           _s(43.95230, -71.36980, 3.0, "solar", False, "valley",
                             "Piper Trail trailhead (Rt 16)"),
    # ── Moosilauke ───────────────────────────────────────────────────────────
    "ravine_lodge":       _s(43.99870, -71.81570, 4.0, "grid", True, "gateway",
                             "Dartmouth Moosilauke Ravine Lodge"),
    "moosilauke_summit":  _s(44.02440, -71.83140, 3.0, "solar", False, "ridge",
                             "Mt. Moosilauke summit"),
    "kinsman_notch":      _s(44.03930, -71.79240, 3.0, "solar", False, "valley",
                             "Kinsman Notch / Beaver Brook trailhead"),
    "glencliff_th":       _s(43.98920, -71.89100, 3.0, "solar", False, "valley",
                             "Glencliff AT trailhead"),
    # ── Carters / Moriah / Baldfaces (east of Rt 16) ─────────────────────────
    "gorham_info":        _s(44.38790, -71.17280, 4.0, "grid", True, "gateway",
                             "Gorham town common info booth"),
    "carter_dome":        _s(44.26710, -71.17890, 3.0, "solar", False, "ridge",
                             "Carter Dome summit"),
    "imp_shelter":        _s(44.29980, -71.15810, 3.0, "solar", False, "shelter",
                             "Imp campsite"),
    "moriah_summit":      _s(44.34090, -71.12920, 3.0, "solar", False, "ridge",
                             "Mt. Moriah summit"),
    "baldface_s":         _s(44.23480, -71.06850, 3.0, "solar", False, "ridge",
                             "South Baldface ledges"),
    # ── Mahoosucs ────────────────────────────────────────────────────────────
    "mt_hayes":           _s(44.40530, -71.13570, 3.0, "solar", False, "ridge",
                             "Mt. Hayes (Mahoosuc Trail S end)"),
    "gentian_pond":       _s(44.42780, -71.08170, 3.0, "solar", False, "shelter",
                             "Gentian Pond shelter"),
    "success_summit":     _s(44.47070, -71.03920, 3.0, "solar", False, "ridge",
                             "Mt. Success summit"),
    # ── Kilkenny / North Country ─────────────────────────────────────────────
    "berlin_gateway":     _s(44.46870, -71.18510, 4.0, "grid", True, "gateway",
                             "Berlin city facility (Rt 110)"),
    "cabot_summit":       _s(44.50440, -71.41400, 3.0, "solar", False, "ridge",
                             "Mt. Cabot (cabin site)"),
    "unknown_pond":       _s(44.51730, -71.36880, 3.0, "solar", False, "shelter",
                             "Unknown Pond campsite"),
    "percy_peaks":        _s(44.57370, -71.42600, 3.0, "solar", False, "ridge",
                             "North Percy Peak"),
    "nash_stream_th":     _s(44.58500, -71.45000, 3.0, "solar", False, "valley",
                             "Nash Stream Rd trailhead"),
    # ── Waumbek / Cherry ─────────────────────────────────────────────────────
    "waumbek_summit":     _s(44.42350, -71.41100, 3.0, "solar", False, "ridge",
                             "Mt. Waumbek summit"),
    "cherry_mtn":         _s(44.34240, -71.44950, 3.0, "solar", False, "ridge",
                             "Cherry Mtn (Mt. Martha)"),
    # ── Cardigan ─────────────────────────────────────────────────────────────
    "cardigan_lodge":     _s(43.64990, -71.88450, 4.0, "grid", True, "gateway",
                             "AMC Cardigan Lodge"),
    "cardigan_summit":    _s(43.64960, -71.91470, 10.0, "solar", False, "ridge",
                             "Mt. Cardigan summit (fire tower)"),
    # ── Sunapee / Ragged ─────────────────────────────────────────────────────
    "sunapee_summit":     _s(43.33160, -72.08040, 6.0, "grid", True, "gateway",
                             "Mt. Sunapee ski summit station"),
    "ragged_mtn":         _s(43.48470, -71.84200, 3.0, "solar", False, "ridge",
                             "Ragged Mtn summit"),
    # ── Belknaps / Ossipees ──────────────────────────────────────────────────
    "gunstock_top":       _s(43.51570, -71.37760, 6.0, "grid", True, "gateway",
                             "Gunstock ski summit station"),
    "major_summit":       _s(43.51340, -71.38480, 3.0, "solar", False, "ridge",
                             "Mt. Major summit"),
    "shaw_summit":        _s(43.78680, -71.30190, 3.0, "solar", False, "ridge",
                             "Mt. Shaw (Ossipee ring)"),
    # ── Monadnock ────────────────────────────────────────────────────────────
    "monadnock_hq":       _s(42.84510, -72.08770, 4.0, "grid", True, "gateway",
                             "Monadnock State Park HQ"),
    "monadnock_summit":   _s(42.86110, -72.10810, 3.0, "solar", False, "ridge",
                             "Mt. Monadnock summit"),
    "dublin_th":          _s(42.88170, -72.06210, 3.0, "solar", False, "valley",
                             "Dublin Trail trailhead"),
    # ── Pack Monadnock ───────────────────────────────────────────────────────
    "miller_hq":          _s(42.85830, -71.88940, 4.0, "grid", True, "gateway",
                             "Miller State Park HQ (Rt 101)"),
    "pack_monadnock":     _s(42.86160, -71.87810, 10.0, "solar", False, "ridge",
                             "Pack Monadnock summit (fire tower)"),
    # ── Smarts / AT corridor west ────────────────────────────────────────────
    "smarts_mtn":         _s(43.82680, -72.03730, 10.0, "solar", False, "ridge",
                             "Smarts Mtn (fire tower)"),
    "lyme_dorchester_th": _s(43.79170, -72.07000, 3.0, "solar", False, "valley",
                             "Lyme-Dorchester Rd AT trailhead"),
    # ── west / south / far-north coverage (audit round 2: NH F&G responds
    #    statewide, not just the Whites) ────────────────────────────────────────
    "winslow_hq":         _s(43.39160, -71.86200, 4.0, "grid", True, "gateway",
                             "Winslow State Park HQ (Mt. Kearsarge)"),
    "kearsarge_summit":   _s(43.38310, -71.85740, 10.0, "solar", False, "ridge",
                             "Mt. Kearsarge summit (fire tower)"),
    "cranmore_top":       _s(44.05790, -71.10920, 6.0, "grid", True, "gateway",
                             "Cranmore ski summit (North Conway)"),
    "kearsarge_north":    _s(44.06740, -71.07460, 10.0, "solar", False, "ridge",
                             "Kearsarge North (fire tower)"),
    "pawtuckaway_hq":     _s(43.10190, -71.16000, 4.0, "grid", True, "gateway",
                             "Pawtuckaway State Park HQ"),
    "pawtuckaway_tower":  _s(43.08470, -71.18330, 10.0, "solar", False, "ridge",
                             "Pawtuckaway South Mtn (fire tower)"),
    "pisgah_hq":          _s(42.83700, -72.42900, 4.0, "grid", True, "gateway",
                             "Pisgah State Park entrance (Rt 63)"),
    "pisgah_ridge":       _s(42.84980, -72.44070, 3.0, "solar", False, "ridge",
                             "Pisgah ridge ledge"),
    "uncanoonuc_s":       _s(42.99230, -71.50600, 6.0, "grid", True, "gateway",
                             "South Uncanoonuc (comm-tower site, grid)"),
    "blue_job":           _s(43.32830, -71.10850, 10.0, "grid", True, "gateway",
                             "Blue Job Mtn (fire tower)"),
    "balsams_gateway":    _s(44.87200, -71.31800, 4.0, "grid", True, "gateway",
                             "The Balsams / Dixville Notch facility"),
    "table_rock":         _s(44.86600, -71.30900, 3.0, "solar", False, "ridge",
                             "Table Rock, Dixville Notch"),
    "pittsburg_village":  _s(45.05290, -71.39380, 4.0, "grid", True, "gateway",
                             "Pittsburg village facility (Rt 3)"),
    "magalloway_tower":   _s(45.06390, -71.15250, 10.0, "solar", True, "gateway",
                             "Mt. Magalloway fire tower (LTE backhaul at tower [SITE-SURVEY])"),
    # ── gap-fix iteration 3: one deliberate fix per stranded site from
    #    audit_coverage.py round 1. Fire towers get their real ~10 m height;
    #    new gateways are real powered facilities (ski areas, dams, estates). ─
    "pulpit_rock":        _s(44.26200, -71.19900, 3.0, "solar", False, "ridge",
                             "Pulpit Rock rim above Carter Notch hut"),
    "tremont_summit":     _s(44.07600, -71.42600, 3.0, "solar", False, "ridge",
                             "Mt. Tremont summit (Sawyer River overlook)"),
    "noon_peak":          _s(43.92680, -71.49900, 3.0, "solar", False, "ridge",
                             "Noon Peak (Sandwich Dome ↔ Waterville ridge)"),
    "dickey_ledges":      _s(43.91190, -71.57500, 3.0, "solar", False, "ridge",
                             "Dickey Mtn open ledges"),
    "tecumseh_ski_top":   _s(43.96000, -71.53500, 6.0, "grid", True, "gateway",
                             "Waterville Valley ski summit (Tecumseh)"),
    "blue_ridge_ledge":   _s(44.03200, -71.81500, 3.0, "solar", False, "ridge",
                             "Moosilauke NE shoulder above Kinsman Notch"),
    "north_carter":       _s(44.30130, -71.15330, 3.0, "solar", False, "ridge",
                             "North Carter summit (Imp shelter link)"),
    "the_horn":           _s(44.51900, -71.39900, 3.0, "solar", False, "ridge",
                             "The Horn (bare knob, Kilkenny ridge)"),
    "victor_head":        _s(44.59000, -71.42500, 3.0, "solar", False, "ridge",
                             "Victor Head ledge above Stark"),
    "ragged_ski_base":    _s(43.48000, -71.82800, 4.0, "grid", True, "gateway",
                             "Ragged Mtn Resort base lodge"),
    "castle_clouds":      _s(43.73260, -71.30680, 4.0, "grid", True, "gateway",
                             "Castle in the Clouds (Ossipee ring, power)"),
    "dartmouth_skiway":   _s(43.78830, -72.09640, 4.0, "grid", True, "gateway",
                             "Dartmouth Skiway base (Lyme)"),
    "holts_ledge":        _s(43.80500, -72.08200, 3.0, "solar", False, "ridge",
                             "Holts Ledge (AT, above the Skiway)"),
    "first_lake_dam":     _s(45.09300, -71.28700, 4.0, "grid", True, "gateway",
                             "First Connecticut Lake dam (Pittsburg)"),
    # ── gap-fix iteration 2 (each fixes a specific isolated cluster) ─────────
    "moosilauke_s_peak":  _s(44.01810, -71.83900, 3.0, "solar", False, "ridge",
                             "Moosilauke South Peak (lodge overlook)"),
    "belknap_summit":     _s(43.50810, -71.42640, 10.0, "solar", False, "ridge",
                             "Belknap Mtn (fire tower; Major↔Gunstock)"),
    "newbury_station":    _s(43.32120, -72.03310, 4.0, "grid", True, "gateway",
                             "Newbury harbor facility (Sunapee E side)"),
    "kilkenny_lookout":   _s(44.48800, -71.39500, 3.0, "solar", False, "ridge",
                             "Kilkenny ridge ledge (Cabot↔Berlin)"),
    "stark_village":      _s(44.60000, -71.40800, 4.0, "grid", True, "gateway",
                             "Stark village facility (Percys/Nash Stream)"),
    "signal_ridge":       _s(44.08900, -71.45300, 3.0, "solar", False, "ridge",
                             "Signal Ridge (Carrigain↔Sawyer River)"),
    # ── gap-fix iteration 4 (audit round 2: one fix per remaining strand) ────
    "white_ledge_cg":     _s(43.92800, -71.36200, 4.0, "grid", True, "gateway",
                             "White Ledge USFS campground (Rt 16, Chocorua)"),
    "notchland_inn":      _s(44.10600, -71.39800, 4.0, "grid", True, "gateway",
                             "Notchland Inn (Rt 302, Sawyer River)"),
    "mt_hight":           _s(44.26980, -71.17280, 3.0, "solar", False, "ridge",
                             "Mt. Hight (bald summit, Carter ridge)"),
    "south_carter":       _s(44.27950, -71.16700, 3.0, "solar", False, "ridge",
                             "South Carter summit"),
    "piper_mtn_belknap":  _s(43.51000, -71.40200, 3.0, "solar", False, "ridge",
                             "Piper Mtn (Gunstock↔Belknap ridge)"),
    "jennings_peak":      _s(43.90680, -71.47900, 3.0, "solar", False, "ridge",
                             "Jennings Peak (Sandwich Dome spur)"),
    "welch_ledges":       _s(43.90200, -71.57800, 3.0, "solar", False, "ridge",
                             "Welch Mtn open ledges"),
    "the_bulge":          _s(44.51000, -71.40800, 3.0, "solar", False, "ridge",
                             "The Bulge (Cabot↔Horn col)"),
    "turtleback_mtn":     _s(43.75500, -71.31500, 3.0, "solar", False, "ridge",
                             "Turtleback Mtn (Castle trail network)"),
    "lambert_ridge":      _s(43.81500, -72.06000, 3.0, "solar", False, "ridge",
                             "Lambert Ridge ledges (AT, Smarts)"),
    "black_cap":          _s(44.05600, -71.08600, 3.0, "solar", False, "ridge",
                             "Black Cap summit (Green Hills)"),
    "second_lake_dam":    _s(45.12800, -71.17500, 4.0, "grid", True, "gateway",
                             "Second Connecticut Lake dam"),
    # ── gap-fix iteration 5: sub-1.35 km ridge chains (short-link policy) ────
    "middle_carter":      _s(44.29210, -71.15870, 3.0, "solar", False, "ridge",
                             "Middle Carter summit"),
    "zeta_pass":          _s(44.28460, -71.16520, 3.0, "solar", False, "ridge",
                             "Zeta Pass col (Carter ridge)"),
    "smarts_ranger_ledge": _s(43.82000, -72.04800, 3.0, "solar", False, "ridge",
                             "Smarts SW shoulder ledge (AT)"),
    "hurricane_col":      _s(44.06200, -71.07900, 3.0, "solar", False, "ridge",
                             "Hurricane Mtn col (Green Hills)"),
    "cranmore_ledge":     _s(44.05700, -71.09700, 3.0, "solar", False, "ridge",
                             "Cranmore E ledge (Black Cap link)"),
    "bald_knob_ossipee":  _s(43.74000, -71.29800, 3.0, "solar", False, "ridge",
                             "Bald Knob (Castle in the Clouds)"),
    "mt_roberts":         _s(43.74600, -71.28900, 3.0, "solar", False, "ridge",
                             "Mt. Roberts summit (Ossipee ring)"),
    "faraway_ledge":      _s(43.75800, -71.28800, 3.0, "solar", False, "ridge",
                             "Faraway Mtn ledge (Ossipee ring)"),
    "ossipee_saddle":     _s(43.76800, -71.29100, 3.0, "solar", False, "ridge",
                             "Ossipee ring saddle"),
    "black_snout":        _s(43.77800, -71.29900, 3.0, "solar", False, "ridge",
                             "Black Snout spur (Mt. Shaw)"),
    # ── coverage round 6: the regions a NH hiker would name instantly ────────
    # Squam Range / Red Hill (top-10 statewide traffic)
    "rockywold_camps":    _s(43.77900, -71.53800, 4.0, "grid", True, "gateway",
                             "Rockywold-Deephaven camps (Squam, power)"),
    "morgan_percival":    _s(43.78980, -71.55210, 3.0, "solar", False, "ridge",
                             "Morgan-Percival col (Squam Range)"),
    "rattlesnake_west":   _s(43.78620, -71.50820, 3.0, "solar", False, "ridge",
                             "West Rattlesnake ledges (Squam)"),
    "red_hill_tower":     _s(43.75570, -71.46980, 10.0, "solar", False, "ridge",
                             "Red Hill fire tower"),
    # Rumney Rocks / Stinson (climbing SAR hotspot)
    "rumney_village":     _s(43.80530, -71.81260, 4.0, "grid", True, "gateway",
                             "Rumney village facility"),
    "stinson_summit":     _s(43.83950, -71.78290, 3.0, "solar", False, "ridge",
                             "Stinson Mtn summit (old tower site)"),
    "rattlesnake_rumney": _s(43.79680, -71.75900, 3.0, "solar", False, "ridge",
                             "Rattlesnake Mtn ledges (Rumney)"),
    "rumney_cliff_top":   _s(43.80800, -71.72600, 3.0, "solar", False, "ridge",
                             "Rumney Rocks cliff top (Rattlesnake Mtn crag)"),
    # Pemi interior + Hale + Twin Mountain
    "loon_summit":        _s(44.03600, -71.62130, 6.0, "grid", True, "gateway",
                             "Loon Mtn gondola summit (power)"),
    "owls_head_slide":    _s(44.12300, -71.60130, 2.0, "battery", False, "portable",
                             "Owl's Head slide (SAR-deployed portable — Pemi Wilderness)"),
    "thirteen_falls":     _s(44.15230, -71.59080, 2.0, "battery", False, "portable",
                             "Thirteen Falls (SAR-deployed portable — Pemi Wilderness)"),
    "mt_hale":            _s(44.18450, -71.51830, 3.0, "solar", False, "ridge",
                             "Mt. Hale summit clearing"),
    "twin_mountain_village": _s(44.25880, -71.54360, 4.0, "grid", True, "gateway",
                             "Twin Mountain village (Rt 3/302)"),
    "sugarloaf_middle":   _s(44.24000, -71.49800, 3.0, "solar", False, "ridge",
                             "Middle Sugarloaf ledges (Zealand Rd)"),
    # Dry River Wilderness
    "isolation_davis":    _s(44.22160, -71.31600, 2.0, "battery", False, "portable",
                             "Mt. Isolation / Davis Path (SAR portable — Dry River Wilderness)"),
    # Wild River / Evans Notch / Jackson
    "wild_river_cg":      _s(44.30640, -71.05610, 4.0, "grid", True, "gateway",
                             "Wild River campground (USFS road [SITE-SURVEY])"),
    "wild_river_blue_brook": _s(44.28950, -71.10420, 2.0, "battery", False, "portable",
                             "Blue Brook (SAR portable — Wild River Wilderness)"),
    "north_baldface":     _s(44.24480, -71.07840, 3.0, "solar", False, "ridge",
                             "North Baldface ledges"),
    "jackson_village":    _s(44.14360, -71.18500, 4.0, "grid", True, "gateway",
                             "Jackson village (Rt 16A)"),
    "doublehead_n":       _s(44.15980, -71.15250, 6.0, "solar", False, "ridge",
                             "North Doublehead (USFS cabin)"),
    "iron_mtn":           _s(44.11020, -71.24700, 3.0, "solar", False, "ridge",
                             "Iron Mtn ledges (Jackson)"),
    # AT west: the Smarts↔Moosilauke gap
    "mt_cube":            _s(43.89600, -72.02290, 3.0, "solar", False, "ridge",
                             "Mt. Cube quartzite ledges (AT)"),
    # Sandwich Range south side
    "mead_base":          _s(43.81800, -71.44800, 4.0, "grid", True, "gateway",
                             "Mead Base scout camp (Sandwich, power)"),
    "mt_israel":          _s(43.83180, -71.44200, 3.0, "solar", False, "ridge",
                             "Mt. Israel summit"),
    "flat_mtn_pond":      _s(43.87900, -71.38800, 2.0, "battery", False, "portable",
                             "Flat Mtn Pond (SAR portable — Sandwich Range Wilderness)"),
    # Lakes region east
    "green_mtn_effingham": _s(43.77020, -71.06280, 10.0, "solar", True, "gateway",
                             "Green Mtn fire tower (Effingham; tower backhaul [SITE-SURVEY])"),
    # South: Bear Brook, Crotched, Wapack
    "bear_brook_hq":      _s(43.16600, -71.39400, 4.0, "grid", True, "gateway",
                             "Bear Brook State Park HQ"),
    "bear_brook_tower":   _s(43.15800, -71.36700, 10.0, "solar", False, "ridge",
                             "Catamount Hill fire tower (Bear Brook)"),
    "crotched_base":      _s(42.99500, -71.86900, 4.0, "grid", True, "gateway",
                             "Crotched Mtn ski base lodge"),
    "crotched_summit":    _s(42.99830, -71.87730, 3.0, "solar", False, "ridge",
                             "Crotched Mtn summit"),
    "temple_mtn_ledges":  _s(42.84720, -71.85290, 3.0, "solar", False, "ridge",
                             "Temple Mtn ledges (Wapack)"),
    # Monadnock–Sunapee Greenway
    "washington_town":    _s(43.17600, -72.09700, 4.0, "grid", True, "gateway",
                             "Washington town center (Greenway)"),
    "lovewell_mtn":       _s(43.16110, -72.06000, 3.0, "solar", False, "ridge",
                             "Lovewell Mtn summit (Greenway)"),
    "pillsbury_sp":       _s(43.23600, -72.09800, 3.0, "solar", False, "valley",
                             "Pillsbury State Park"),
    # Pisgah west side
    "kilburn_th":         _s(42.86200, -72.46900, 3.0, "solar", False, "valley",
                             "Kilburn Loop trailhead (Pisgah W)"),
    # Cohos / far north infill
    "milan_hill":         _s(44.61200, -71.22500, 10.0, "grid", True, "gateway",
                             "Milan Hill fire tower + SP (power [SITE-SURVEY])"),
    "sugarloaf_nash":     _s(44.64810, -71.39800, 3.0, "solar", False, "ridge",
                             "Sugarloaf Mtn (Nash Stream)"),
    "deer_mtn_pittsburg": _s(45.14000, -71.35000, 3.0, "solar", False, "ridge",
                             "Deer Mtn (Pittsburg, old tower)"),
    # Kanc east
    "champney_th":        _s(43.99950, -71.29650, 3.0, "solar", False, "valley",
                             "Champney Falls trailhead (Kanc)"),
    # ── round 6b: strand closures — real gateways + ≤1.35 km relay chains ────
    "buffalo_rd_lot":     _s(43.80230, -71.72910, 4.0, "grid", True, "gateway",
                             "Rumney Rocks USFS parking (Buffalo Rd [SITE-SURVEY])"),
    "stinson_lake_gw":    _s(43.85200, -71.78700, 4.0, "grid", True, "gateway",
                             "Stinson Lake settlement (power [SITE-SURVEY])"),
    "attitash_base":      _s(44.08280, -71.22900, 4.0, "grid", True, "gateway",
                             "Attitash ski base lodge (Rt 302)"),
    "iron_s_ledge":       _s(44.10200, -71.24000, 3.0, "solar", False, "ridge",
                             "Iron Mtn south ledge"),
    "rocky_branch_knoll": _s(44.09300, -71.23500, 3.0, "solar", False, "ridge",
                             "Rocky Branch knoll (Iron↔Attitash)"),
    "mt_cube_farm":       _s(43.90800, -72.00500, 4.0, "grid", True, "gateway",
                             "Mt. Cube Farm (Rt 25A, power)"),
    "cube_s_ledge":       _s(43.90100, -72.01500, 3.0, "solar", False, "ridge",
                             "Mt. Cube south ledge (AT)"),
    "deer_mtn_cg":        _s(45.13500, -71.34500, 4.0, "grid", True, "gateway",
                             "Deer Mtn state campground (Rt 3 [SITE-SURVEY])"),
    # Monadnock–Sunapee Greenway chain (Washington ↔ Pillsbury, wooded corridor)
    "millen_pond":        _s(43.18400, -72.09600, 3.0, "solar", False, "ridge",
                             "Millen Pond ledge (Greenway)"),
    "faxon_hill":         _s(43.19300, -72.09000, 3.0, "solar", False, "ridge",
                             "Faxon Hill (Greenway)"),
    "greenway_mid":       _s(43.20400, -72.08600, 3.0, "solar", False, "ridge",
                             "Greenway mid ledge"),
    "kittredge_hill":     _s(43.21400, -72.08800, 3.0, "solar", False, "ridge",
                             "Kittredge Hill (Greenway)"),
    "bryant_ledge":       _s(43.22500, -72.09200, 3.0, "solar", False, "ridge",
                             "Bryant ledge (Pillsbury S)"),
    # Pisgah west chain
    "pisgah_w_knoll":     _s(42.85400, -72.45200, 3.0, "solar", False, "ridge",
                             "Pisgah west knoll"),
    "kilburn_ridge":      _s(42.85900, -72.46100, 3.0, "solar", False, "ridge",
                             "Kilburn ridge (Pisgah W)"),
    # ── round 7: western-margin audit (Connecticut River side) ───────────────
    "moose_mtn_at":       _s(43.73000, -72.14200, 3.0, "solar", False, "ridge",
                             "Moose Mtn South Peak (AT, Hanover)"),
    "black_mtn_benton":   _s(44.04100, -71.90500, 3.0, "solar", False, "ridge",
                             "Black Mtn ledges (Benton)"),
    "prospect_weeks":     _s(44.43350, -71.57500, 10.0, "grid", True, "gateway",
                             "Mt. Prospect / Weeks SP (tower, auto road, power)"),
    "moose_mtn_lodge":    _s(43.72000, -72.16000, 4.0, "grid", True, "gateway",
                             "Moose Mountain Lodge (Hanover [SITE-SURVEY])"),
    "moose_s_ledge":      _s(43.72500, -72.15100, 3.0, "solar", False, "ridge",
                             "Moose Mtn south ledge (AT)"),
}
